# PPH / Cord clamping and postpartum anemia: robust publication-oriented analysis script
# Version 14: adapted for the fully English translated dataset schema
# Author: generated by Goksu Goc
# Run from the repository root or from the analysis/ folder; the public dataset is resolved from data/PPH_CordClamping.csv.

options(stringsAsFactors = FALSE)
set.seed(20260430)

# -----------------------------
# 0. User settings
# -----------------------------
INPUT_CANDIDATES <- c(
  "data/PPH_CordClamping.csv",
  "../data/PPH_CordClamping.csv",
  "PPH_CordClamping.csv",
  "PPH_CordClamping_Fully_English_PublicationReady.csv",
  "PPH_CordClamping_Fully_English_PublicationReady.xlsx",
  "PPH_CordClamping_Final_PublicationReady_English.csv",
  "PPH_CordClamping_Final_PublicationReady_English.xlsx"
)
OUTPUT_DIR <- "analysis_outputs_cord_clamping_v14_fully_english"
PRIMARY_EXPOSURE <- "exposure_guideline_delay"
MIN_SUBGROUP_N <- 30
TRIM_Q <- c(0.01, 0.99)
EXPECTED_DATE_RANGE <- as.Date(c("2022-01-01", "2024-12-31"))

# -----------------------------
# 1. Packages
# -----------------------------
required_pkgs <- c(
  "tidyverse", "readr", "readxl", "janitor", "lubridate", "broom",
  "tableone", "WeightIt", "cobalt", "survey", "sandwich", "lmtest",
  "MatchIt", "logistf", "EValue", "splines", "stringr", "forcats"
)
install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg, dependencies = TRUE)
}
invisible(lapply(required_pkgs, install_if_missing))
suppressPackageStartupMessages({
  library(tidyverse); library(readr); library(readxl); library(janitor)
  library(lubridate); library(broom); library(tableone); library(WeightIt)
  library(cobalt); library(survey); library(sandwich); library(lmtest)
  library(MatchIt); library(logistf); library(EValue); library(splines)
})

dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)
SCRIPT_VERSION <- "v14_fully_english_schema_2026-04-30"
message("Running PPH Cord Clamping integrated analysis script ", SCRIPT_VERSION)
write_text <- function(x, path) writeLines(as.character(x), con = path, useBytes = TRUE)
log_step <- function(x) message(sprintf("[%s] %s", format(Sys.time(), "%H:%M:%S"), x))
`%||%` <- function(x, y) if (is.null(x)) y else x

# Safe output helpers for empty/error model tables. Some models legitimately return
# only an error column or zero rows; downstream filtering must not assume a term column.
standardize_result_table <- function(x) {
  if (is.null(x)) x <- tibble()
  if (!is.data.frame(x)) x <- tibble(message = as.character(x))
  x <- tibble::as_tibble(x)

  # Harmonise broom/survey naming variants before binding outputs.
  if ("std.error" %in% names(x) && !"std_error" %in% names(x)) x <- dplyr::rename(x, std_error = std.error)
  if ("p.value" %in% names(x) && !"p_value" %in% names(x)) x <- dplyr::rename(x, p_value = p.value)
  if ("conf.low" %in% names(x) && !"conf_low" %in% names(x)) x <- dplyr::rename(x, conf_low = conf.low)
  if ("conf.high" %in% names(x) && !"conf_high" %in% names(x)) x <- dplyr::rename(x, conf_high = conf.high)

  required <- c("term", "outcome", "model", "estimate", "std_error", "statistic",
                "conf_low", "conf_high", "estimate_exp", "conf_low_exp", "conf_high_exp",
                "p_value", "n_obs", "n_events", "error")
  for (nm in required) {
    if (!nm %in% names(x)) x[[nm]] <- NA
  }
  x
}
safe_write_csv <- function(x, path) {
  if (is.null(x)) x <- tibble()
  if (!is.data.frame(x)) x <- tibble(value = as.character(x))
  readr::write_csv(tibble::as_tibble(x), path)
}

safe_term_filter <- function(x, pattern) {
  x <- standardize_result_table(x)
  if (nrow(x) == 0) return(x[0, , drop = FALSE])
  x %>%
    dplyr::filter(!is.na(.data$term),
                  stringr::str_detect(as.character(.data$term), pattern))
}

safe_outcome_term_filter <- function(x, outcome_name, pattern) {
  x <- standardize_result_table(x)
  if (nrow(x) == 0) return(x[0, , drop = FALSE])
  x %>%
    dplyr::filter(.data$outcome == outcome_name,
                  !is.na(.data$term),
                  stringr::str_detect(as.character(.data$term), pattern))
}

safe_add_source <- function(x, source_name) {
  x <- standardize_result_table(x)
  if (nrow(x) == 0) return(tibble::tibble(source = source_name))
  x %>% dplyr::mutate(source = source_name)
}



# -----------------------------
# 2. Import and name helpers
# -----------------------------
existing <- INPUT_CANDIDATES[file.exists(INPUT_CANDIDATES)]
if (length(existing) == 0) stop("No input dataset found. Put PPH_CordClamping.csv in the working directory.")
INPUT_FILE <- existing[1]
log_step(paste("Using input file:", INPUT_FILE))

raw <- if (grepl("\\.xlsx$", INPUT_FILE, ignore.case = TRUE)) {
  readxl::read_excel(INPUT_FILE)
} else {
  readr::read_csv(INPUT_FILE, locale = locale(encoding = "UTF-8"), show_col_types = FALSE, guess_max = 10000)
}

normalize_name <- function(x) {
  x <- as.character(x)
  x <- iconv(x, from = "UTF-8", to = "ASCII//TRANSLIT")
  x <- tolower(x)
  x <- gsub("[^a-z0-9]+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}
orig_names <- names(raw)
names(raw) <- make.unique(normalize_name(names(raw)), sep = "_")
name_map <- tibble(original_name = orig_names, normalized_name = names(raw))
write_csv(name_map, file.path(OUTPUT_DIR, "00_imported_column_name_map.csv"))

# -----------------------------
# 2a. Calendar-time backstop for month-resolution public datasets
# -----------------------------
# This repository publishes calendar time at month resolution (delivery_month,
# delivery_year_quarter, delivery_month_numeric) to reduce re-identification
# risk. The downstream pipeline expects a day-level `delivery_date` column.
# When the raw file does not carry a day-level `delivery_date_iso` field but
# does carry `delivery_month` (YYYY-MM), synthesize delivery_date_iso as the
# 15th of the stated month as a neutral mid-month anchor for the natural
# cubic spline. Day-of-month variation is absent by design, but with df = 3
# the spline is effectively a smooth function of months-since-anchor and the
# estimates are statistically equivalent to the day-level model at the
# precision reported.
if (!"delivery_date_iso" %in% names(raw) && "delivery_month" %in% names(raw)) {
  log_step("delivery_date_iso absent; synthesizing day-level dates from delivery_month (15th-of-month anchor) for spline construction.")
  raw <- raw %>%
    mutate(
      delivery_date_iso = if_else(
        !is.na(delivery_month) & nzchar(as.character(delivery_month)),
        paste0(as.character(delivery_month), "-15"),
        NA_character_
      )
    )
}

# English-schema audit for the translated publication-ready dataset.
expected_english_columns <- c(
  "study_id", "delivery_date_iso", "anemia_status", "anemia_severity",
  "pre_delivery_hemoglobin_g_dl", "postpartum_6h_hemoglobin_g_dl", "hemoglobin_drop_g_dl",
  "weight_kg", "height_cm", "parity", "body_mass_index_kg_m2", "cord_clamping_group",
  "cord_clamping_delay_seconds", "number_of_fetuses", "maternal_comorbidity",
  "pregnancy_complication", "iron_use_during_pregnancy", "delivery_mode",
  "iv_ferric_carboxymaltose_use_during_pregnancy", "uterotonic_agent",
  "additional_uterotonic_used", "additional_surgical_suture_used",
  "blood_transfusion_needed", "gravidity_group", "grand_multiparity",
  "plurality_group", "postpartum_hemorrhage"
)
english_schema_audit <- tibble(
  expected_column = expected_english_columns,
  present = expected_column %in% names(raw)
)
write_csv(english_schema_audit, file.path(OUTPUT_DIR, "00_english_schema_audit.csv"))
if (sum(english_schema_audit$present) >= 20) {
  log_step("Detected translated English dataset schema.")
}

find_col <- function(data, aliases = character(), patterns = character()) {
  nm <- names(data)
  aliases <- normalize_name(aliases)
  hit <- intersect(aliases, nm)
  if (length(hit) > 0) return(hit[1])
  for (p in patterns) {
    h <- nm[str_detect(nm, regex(p, ignore_case = TRUE))]
    if (length(h) > 0) return(h[1])
  }
  NA_character_
}
get_col <- function(data, aliases = character(), patterns = character(), default = NA) {
  cc <- find_col(data, aliases, patterns)
  if (is.na(cc)) rep(default, nrow(data)) else data[[cc]]
}
num <- function(x) suppressWarnings(as.numeric(str_replace_all(as.character(x), ",", ".")))
chr <- function(x) str_squish(as.character(x))
low <- function(x) str_to_lower(chr(x))
yn01 <- function(x) {
  # Preserve true missing/blank values as NA. Explicit No/0 values remain 0.
  z <- low(x)
  case_when(
    is.na(z) | z %in% c("", "na", "nan", "missing", "unknown") ~ NA_integer_,
    z %in% c("1", "yes", "y", "true", "evet", "e") ~ 1L,
    z %in% c("0", "no", "n", "false", "hayir", "hayır", "h", "none", "none recorded", "no recorded") ~ 0L,
    TRUE ~ suppressWarnings(as.integer(as.numeric(z)))
  )
}
yn_factor <- function(x) factor(if_else(yn01(x) == 1L, "Yes", "No", missing = NA_character_), levels = c("No", "Yes"))
none_if_blank <- function(x) {
  z <- chr(x)
  z[z == "" | z == "NA" | is.na(z)] <- "None recorded"
  z
}

# -----------------------------
# 3. Harmonise raw/English dataset into analysis schema
# -----------------------------
map_anemia_status <- function(x) {
  z <- low(x)
  case_when(
    str_detect(z, "non[- ]?anemic|non[- ]?anaemic|normal|no anemia|no anaemia") ~ "Non-anemic",
    str_detect(z, "anemic|anaemic|anemia|anaemia") ~ "Anemic",
    TRUE ~ NA_character_
  )
}
map_anemia_severity <- function(x) {
  z <- low(x)
  case_when(
    str_detect(z, "no anemia|no anaemia|normal|none|no ana?emia") ~ "Normal",
    str_detect(z, "hafif|mild") ~ "Mild",
    str_detect(z, "orta|moderate") ~ "Moderate",
    str_detect(z, "agir|ağır|severe") ~ "Severe",
    TRUE ~ NA_character_
  )
}
map_delivery <- function(x) {
  z <- low(x)
  case_when(
    z %in% c("1", "vd", "vaginal", "vaginal delivery", "normal", "normal dogum", "nvd") ~ "Vaginal delivery",
    z %in% c("0", "cs", "c/s", "cesarean", "cesarean delivery", "sezaryen", "sezeryan") ~ "Cesarean delivery",
    str_detect(z, "vaj|vag|nvd|normal") ~ "Vaginal delivery",
    str_detect(z, "sez|ces|cs") ~ "Cesarean delivery",
    TRUE ~ NA_character_
  )
}
map_plurality <- function(x, n_fetus = NULL) {
  z <- low(x)
  out <- case_when(
    str_detect(z, "tek|single") ~ "Singleton",
    str_detect(z, "ikiz|cogul|çoğul|twin|multiple") ~ "Multiple pregnancy",
    TRUE ~ NA_character_
  )
  if (!is.null(n_fetus)) {
    out <- if_else(is.na(out) & !is.na(n_fetus) & n_fetus <= 1, "Singleton", out)
    out <- if_else(is.na(out) & !is.na(n_fetus) & n_fetus > 1, "Multiple pregnancy", out)
  }
  out
}
map_n_fetus <- function(x) {
  z <- low(x)
  case_when(
    str_detect(z, "tek|single") ~ 1,
    str_detect(z, "ikiz|twin") ~ 2,
    str_detect(z, "ucuz|trip|üç") ~ 3,
    TRUE ~ num(z)
  )
}
map_gravidity <- function(x) {
  z <- low(x)
  g <- num(x)
  case_when(
    str_detect(z, "primigravida|primi") ~ "Primigravida",
    str_detect(z, "multigravida|multi") ~ "Multigravida",
    is.na(g) ~ NA_character_,
    g <= 1 ~ "Primigravida",
    g > 1 ~ "Multigravida"
  )
}
map_uterotonic <- function(x) {
  z <- chr(x)
  z[z == "" | is.na(z)] <- "None recorded"
  z <- str_to_upper(z)
  z <- case_when(
    str_detect(z, "PABAL") ~ "Carbetocin/Pabal",
    str_detect(z, "OKS|OXY|OXT|SYN") ~ "Oxytocin",
    str_detect(z, "MISO|CYTO") ~ "Misoprostol",
    str_detect(z, "METHER|METILER") ~ "Methylergometrine",
    z %in% c("NONE RECORDED", "NA") ~ "None recorded",
    TRUE ~ str_to_sentence(z)
  )
  z
}
parse_date_any <- function(x) {
  if (inherits(x, "Date")) return(x)
  if (is.numeric(x)) return(as.Date(x, origin = "1899-12-30"))
  xx <- chr(x)
  serial <- suppressWarnings(as.numeric(xx))
  y <- suppressWarnings(ymd(xx))
  idx <- is.na(y); if (any(idx)) y[idx] <- suppressWarnings(mdy(xx[idx]))
  idx <- is.na(y); if (any(idx)) y[idx] <- suppressWarnings(dmy(xx[idx]))
  idx <- is.na(y) & !is.na(serial) & serial > 20000 & serial < 80000
  if (any(idx)) y[idx] <- as.Date(serial[idx], origin = "1899-12-30")
  y
}

derive_cord_delay <- function(data) {
  direct <- get_col(data, c("cord_clamping_delay_seconds", "cord_delay_sec", "cord_clamping_delay_sec"), patterns = c("cord.*delay.*sec|clamp.*delay.*sec"))
  d <- num(direct)
  if (sum(!is.na(d)) > 0) return(d)
  c0 <- yn01(get_col(data, c("kordhemenmiklemplendievet1hayir0"), patterns = c("kord.*hemen|immediate.*clamp")))
  c30 <- yn01(get_col(data, c("kordklemplenmesi30snbeklendimievet1hayir0"), patterns = c("30.*sn|30.*sec")))
  c60 <- yn01(get_col(data, c("kordkelmplenmesi1dkbeklendimievet1hayir0"), patterns = c("1.*dk|1.*min|60.*sec")))
  c120 <- yn01(get_col(data, c("kordklemplenmesi2dkbeklendimievet1hayir0"), patterns = c("2.*dk|2.*min|120.*sec")))
  grp <- low(get_col(data, c("cord_clamping_group", "kkgrup"), patterns = c("kkgrup|cord.*group")))
  out <- rep(NA_real_, nrow(data))
  out[c0 == 1] <- 0
  out[c30 == 1] <- 30
  out[c60 == 1] <- 60
  out[c120 == 1] <- 120
  out[is.na(out) & str_detect(grp, "hemen|immediate")] <- 0
  out[is.na(out) & str_detect(grp, "30")] <- 30
  out[is.na(out) & str_detect(grp, "1.*dk|1.*min|60")] <- 60
  out[is.na(out) & str_detect(grp, "2.*dk|2.*min|120")] <- 120
  out
}

n_fetus <- map_n_fetus(get_col(raw, c("number_of_fetuses", "fetussayisi", "fetus_sayisi", "fetussayisi_1", "fetussayısı"), patterns = c("fetus|fetus.*say")))
cord_delay <- derive_cord_delay(raw)

dat <- tibble(
  study_id = as.character(get_col(raw, c("study_id", "patient_id", "protokol", "protocol_number"), default = seq_len(nrow(raw)))),
  delivery_date = parse_date_any(get_col(raw, c("delivery_date_iso", "delivery_date", "dogum_tarihi", "dogumtarihi"), patterns = c("dogum|delivery.*date"))),
  anemia_status = factor(map_anemia_status(get_col(raw, c("anemia_status", "anemi"))), levels = c("Non-anemic", "Anemic")),
  anemia_severity = factor(map_anemia_severity(get_col(raw, c("anemia_severity", "anemigrup", "anemi_grup"))), levels = c("Normal", "Mild", "Moderate", "Severe")),
  pre_delivery_hemoglobin_g_dl = num(get_col(raw, c("pre_delivery_hemoglobin_g_dl", "preophb", "preop_hb"), patterns = c("pre.*hb|preop"))),
  postpartum_6h_hemoglobin_g_dl = num(get_col(raw, c("postpartum_6h_hemoglobin_g_dl", "popp6_saathb", "popp6_saat_hb"), patterns = c("popp6|post.*6.*hb"))),
  hemoglobin_drop_g_dl = num(get_col(raw, c("hemoglobin_drop_g_dl", "hgfarki", "hg_farki", "hb_drop"), patterns = c("hgfark|hb.*drop|hemo.*drop"))),
  weight_kg = num(get_col(raw, c("weight_kg", "kilo"), patterns = c("kilo|weight"))),
  height_cm = num(get_col(raw, c("height_cm", "boy"), patterns = c("boy|height"))),
  parity = num(get_col(raw, c("parity", "parite"), patterns = c("parite|parity"))),
  body_mass_index_kg_m2 = num(get_col(raw, c("body_mass_index_kg_m2", "bmi"), patterns = c("bmi|mass_index"))),
  number_of_fetuses = n_fetus,
  cord_clamping_delay_seconds = cord_delay,
  maternal_comorbidity = none_if_blank(get_col(raw, c("maternal_comorbidity", "ekhastalik", "ek_hastalik"), patterns = c("ekhast|comorb"))),
  pregnancy_complication = none_if_blank(get_col(raw, c("pregnancy_complication", "gebelikkomplikasyonu", "gebelik_komplikasyonu"), patterns = c("gebelik.*komplik|pregnancy.*comp"))),
  iron_use_during_pregnancy = yn_factor(get_col(raw, c("iron_use_during_pregnancy", "gebeliktefekullanimivar1yok0"), patterns = c("gebelikte.*fe|iron.*preg"))),
  delivery_mode = factor(map_delivery(get_col(raw, c("delivery_mode", "dogumseklics0vd1", "dogum_sekli_cs0vd1", "dogum_sekli_cs0_vd1"), patterns = c("dogum.*sek|delivery.*mode"))), levels = c("Vaginal delivery", "Cesarean delivery")),
  iv_ferric_carboxymaltose_use_during_pregnancy = yn_factor(get_col(raw, c("iv_ferric_carboxymaltose_use_during_pregnancy", "gebelikteferinjektkullanildimievet1hayir0"), patterns = c("ferinjekt.*kullan|carboxymaltose"))),
  uterotonic_agent = factor(map_uterotonic(get_col(raw, c("uterotonic_agent", "uterotonikkullanimi"), patterns = c("uteroton")))),
  additional_uterotonic_used = yn_factor(get_col(raw, c("additional_uterotonic_used", "ekuterotonik"), patterns = c("ekuteroton|additional.*uterotonic"))),
  additional_surgical_suture_used = yn_factor(get_col(raw, c("additional_surgical_suture_used", "ekcerrahisutur"), patterns = c("ekcerrahi|suture"))),
  blood_transfusion_needed = yn_factor(get_col(raw, c("blood_transfusion_needed", "kantransfuzyonihtiyaci", "kan_transfuzyon_ihtiyaci"), patterns = c("kan.*trans|blood.*trans"))),
  gravidity_group = factor(map_gravidity(get_col(raw, c("gravidity_group", "gravidayeni", "gravida_yeni", "gravidayeni_1"), patterns = c("gravid"))), levels = c("Primigravida", "Multigravida")),
  grand_multiparity = yn_factor(get_col(raw, c("grand_multiparity", "grandmprt"), patterns = c("grand"))),
  plurality_group = factor(map_plurality(get_col(raw, c("plurality_group", "cogulgebelik", "cogul_gebelik"), patterns = c("cogul|plural")), n_fetus), levels = c("Singleton", "Multiple pregnancy")),
  postpartum_hemorrhage = yn_factor(get_col(raw, c("postpartum_hemorrhage", "kanama", "pph"), patterns = c("kanama|hemorrhage|pph")))
) %>%
  mutate(
    hemoglobin_drop_g_dl = if_else(is.na(hemoglobin_drop_g_dl) & !is.na(pre_delivery_hemoglobin_g_dl) & !is.na(postpartum_6h_hemoglobin_g_dl), pre_delivery_hemoglobin_g_dl - postpartum_6h_hemoglobin_g_dl, hemoglobin_drop_g_dl),
    body_mass_index_kg_m2 = if_else(is.na(body_mass_index_kg_m2) & !is.na(weight_kg) & !is.na(height_cm) & height_cm > 0, weight_kg / (height_cm / 100)^2, body_mass_index_kg_m2),
    cord_group_4 = factor(case_when(cord_clamping_delay_seconds == 0 ~ "Immediate", cord_clamping_delay_seconds == 30 ~ "Delayed 30 seconds", cord_clamping_delay_seconds == 60 ~ "Delayed 60 seconds", cord_clamping_delay_seconds == 120 ~ "Delayed 120 seconds", TRUE ~ NA_character_), levels = c("Immediate", "Delayed 30 seconds", "Delayed 60 seconds", "Delayed 120 seconds")),
    exposure_guideline_delay = factor(case_when(cord_clamping_delay_seconds >= 60 ~ "Delayed_60s_or_more", cord_clamping_delay_seconds < 60 ~ "Immediate_or_30s", TRUE ~ NA_character_), levels = c("Immediate_or_30s", "Delayed_60s_or_more")),
    exposure_any_delay = factor(case_when(cord_clamping_delay_seconds > 0 ~ "Any_delay", cord_clamping_delay_seconds == 0 ~ "Immediate", TRUE ~ NA_character_), levels = c("Immediate", "Any_delay")),
    exposure_immediate_vs_60plus = factor(case_when(cord_clamping_delay_seconds == 0 ~ "Immediate", cord_clamping_delay_seconds >= 60 ~ "Delayed_60s_or_more", TRUE ~ NA_character_), levels = c("Immediate", "Delayed_60s_or_more")),
    pre_delivery_anemia_hb11 = factor(if_else(pre_delivery_hemoglobin_g_dl < 11, "Yes", "No", missing = NA_character_), levels = c("No", "Yes")),
    postpartum_anemia_hb10 = factor(if_else(postpartum_6h_hemoglobin_g_dl < 10, "Yes", "No", missing = NA_character_), levels = c("No", "Yes")),
    postpartum_anemia_hb11 = factor(if_else(postpartum_6h_hemoglobin_g_dl < 11, "Yes", "No", missing = NA_character_), levels = c("No", "Yes")),
    hb_drop_ge_2g = factor(if_else(hemoglobin_drop_g_dl >= 2, "Yes", "No", missing = NA_character_), levels = c("No", "Yes")),
    maternal_comorbidity_any = factor(if_else(!is.na(maternal_comorbidity) & maternal_comorbidity != "None recorded", "Yes", "No"), levels = c("No", "Yes")),
    pregnancy_complication_any = factor(if_else(!is.na(pregnancy_complication) & pregnancy_complication != "None recorded", "Yes", "No"), levels = c("No", "Yes")),
    delivery_date_valid = !is.na(delivery_date) & delivery_date >= EXPECTED_DATE_RANGE[1] & delivery_date <= EXPECTED_DATE_RANGE[2],
    delivery_year = factor(if_else(delivery_date_valid, as.character(year(delivery_date)), NA_character_)),
    delivery_year_quarter = factor(if_else(delivery_date_valid, paste0(year(delivery_date), "-Q", quarter(delivery_date)), NA_character_)),
    delivery_date_numeric = if_else(delivery_date_valid, as.numeric(delivery_date - EXPECTED_DATE_RANGE[1]), NA_real_),
    delivery_date_invalid_or_missing = factor(if_else(is.na(delivery_date_numeric), "Yes", "No"), levels = c("No", "Yes")),
    analysis_cluster_id = if_else(is.na(study_id), paste0("row_missing_id_", row_number()), as.character(study_id))
  )

# Same patient-date duplicate diagnostics. Repeated study IDs on different dates may represent
# separate pregnancies and are handled with clustered SEs. Rows sharing both study_id and
# delivery_date are more likely to represent duplicate maternal-delivery records, multiple
# infant-level rows for one maternal delivery, or data-entry conflicts; these are flagged and
# excluded in a dedicated sensitivity analysis below.
duplicate_same_day_groups <- dat %>%
  filter(!is.na(study_id), !is.na(delivery_date)) %>%
  group_by(study_id, delivery_date) %>%
  summarise(
    n_rows = n(),
    n_exposure_levels = n_distinct(exposure_guideline_delay, na.rm = TRUE),
    n_cord_delay_values = n_distinct(cord_clamping_delay_seconds, na.rm = TRUE),
    n_delivery_modes = n_distinct(delivery_mode, na.rm = TRUE),
    n_postpartum_hb_values = n_distinct(postpartum_6h_hemoglobin_g_dl, na.rm = TRUE),
    n_postpartum_anemia_values = n_distinct(postpartum_anemia_hb10, na.rm = TRUE),
    n_pph_values = n_distinct(postpartum_hemorrhage, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(n_rows > 1) %>%
  arrange(desc(n_rows), study_id, delivery_date)

duplicate_same_day_keys <- duplicate_same_day_groups %>% select(study_id, delivery_date)
dat <- dat %>%
  left_join(duplicate_same_day_keys %>% mutate(duplicate_same_id_date = "Yes"),
            by = c("study_id", "delivery_date")) %>%
  mutate(duplicate_same_id_date = factor(if_else(is.na(duplicate_same_id_date), "No", "Yes"),
                                         levels = c("No", "Yes")))

duplicate_same_day_rows <- dat %>%
  semi_join(duplicate_same_day_keys, by = c("study_id", "delivery_date")) %>%
  arrange(study_id, delivery_date)

safe_write_csv(duplicate_same_day_groups, file.path(OUTPUT_DIR, "00_duplicate_same_patient_date_groups.csv"))
safe_write_csv(duplicate_same_day_rows, file.path(OUTPUT_DIR, "00_duplicate_same_patient_date_rows.csv"))

# Keep a cleaned analysis dataset for audit.
write_csv(dat, file.path(OUTPUT_DIR, "00_analysis_dataset_harmonised.csv"))

# Calendar-time diagnostics. Cord-clamping practice changed across the study period;
# therefore valid delivery date is included in the primary adjustment/PS models.
calendar_exposure <- dat %>%
  filter(!is.na(delivery_year)) %>%
  count(delivery_year, !!sym(PRIMARY_EXPOSURE), name = "n") %>%
  group_by(delivery_year) %>%
  mutate(percent_within_year = 100 * n / sum(n)) %>%
  ungroup()
safe_write_csv(calendar_exposure, file.path(OUTPUT_DIR, "00_calendar_time_by_exposure.csv"))

calendar_outcomes <- dat %>%
  filter(!is.na(delivery_year)) %>%
  group_by(delivery_year) %>%
  summarise(
    n = n(),
    postpartum_anemia_hb10_rate = mean(postpartum_anemia_hb10 == "Yes", na.rm = TRUE),
    postpartum_hemorrhage_rate = mean(postpartum_hemorrhage == "Yes", na.rm = TRUE),
    blood_transfusion_needed_rate = mean(blood_transfusion_needed == "Yes", na.rm = TRUE),
    .groups = "drop"
  )
safe_write_csv(calendar_outcomes, file.path(OUTPUT_DIR, "00_calendar_outcomes_by_year.csv"))

invalid_dates <- dat %>%
  filter(is.na(delivery_date_numeric)) %>%
  select(any_of(c("study_id", "delivery_date", "cord_clamping_delay_seconds", "delivery_mode", PRIMARY_EXPOSURE)))
safe_write_csv(invalid_dates, file.path(OUTPUT_DIR, "00_invalid_or_missing_delivery_dates_for_calendar_adjustment.csv"))

# -----------------------------
# 4. QC and variable diagnostics
# -----------------------------
qc_overall <- tibble(
  metric = c("Total records", "Unique study IDs", "Missing exposure", "Delayed >=60s", "Immediate/30s", "Missing 6h Hb", "Postpartum anemia Hb<10 events", "Vaginal deliveries", "Cesarean deliveries"),
  value = c(nrow(dat), n_distinct(dat$study_id), sum(is.na(dat[[PRIMARY_EXPOSURE]])), sum(dat[[PRIMARY_EXPOSURE]] == "Delayed_60s_or_more", na.rm = TRUE), sum(dat[[PRIMARY_EXPOSURE]] == "Immediate_or_30s", na.rm = TRUE), sum(is.na(dat$postpartum_6h_hemoglobin_g_dl)), sum(dat$postpartum_anemia_hb10 == "Yes", na.rm = TRUE), sum(dat$delivery_mode == "Vaginal delivery", na.rm = TRUE), sum(dat$delivery_mode == "Cesarean delivery", na.rm = TRUE))
)
write_csv(qc_overall, file.path(OUTPUT_DIR, "00_qc_overall.csv"))
missingness <- tibble(variable = names(dat), missing_n = map_int(dat, ~ sum(is.na(.x))), missing_percent = 100 * missing_n / nrow(dat), nonmissing_distinct = map_int(dat, ~ n_distinct(.x, na.rm = TRUE))) %>% arrange(desc(missing_percent))
write_csv(missingness, file.path(OUTPUT_DIR, "00_missingness_by_variable.csv"))
write_csv(tibble(variable = names(dat), class = map_chr(dat, ~ paste(class(.x), collapse = ";")), levels_or_range = map_chr(dat, function(x) { if (is.factor(x) || is.character(x)) paste(head(unique(na.omit(as.character(x))), 20), collapse = " | ") else paste0("range ", paste(range(x, na.rm = TRUE), collapse = " to ")) })), file.path(OUTPUT_DIR, "00_variable_types.csv"))

# -----------------------------
# 5. Dynamic formula utilities
# -----------------------------
has_2plus <- function(x) n_distinct(x[!is.na(x)]) >= 2
base_covariates <- c("pre_delivery_hemoglobin_g_dl", "body_mass_index_kg_m2", "parity", "delivery_mode", "plurality_group", "grand_multiparity", "iron_use_during_pregnancy", "iv_ferric_carboxymaltose_use_during_pregnancy", "maternal_comorbidity_any", "pregnancy_complication_any", "delivery_date_numeric")
present_base_covariates <- intersect(base_covariates, names(dat))
model_covariate_names <- present_base_covariates[map_lgl(dat[present_base_covariates], has_2plus)]
model_covariates <- c(
  setdiff(model_covariate_names, "delivery_date_numeric"),
  if ("delivery_date_numeric" %in% model_covariate_names) "splines::ns(delivery_date_numeric, df = 3)"
)
write_csv(tibble(covariate = base_covariates, retained = base_covariates %in% model_covariate_names, reason = if_else(base_covariates %in% model_covariate_names, "Retained", "Dropped: missing or <2 levels")), file.path(OUTPUT_DIR, "00_covariate_retention_for_models.csv"))

term_vars <- function(terms) {
  vars <- unique(unlist(str_extract_all(terms, "[A-Za-z_][A-Za-z0-9_]*")))
  setdiff(vars, c("splines", "ns", "I", "log", "poly", "df", "TRUE", "FALSE"))
}
term_available <- function(term, data) all(term_vars(term) %in% names(data))
filter_terms <- function(terms, data) {
  terms <- terms[map_lgl(terms, ~ term_available(.x, data))]
  terms[map_lgl(terms, function(t) {
    vv <- intersect(term_vars(t), names(data))
    if (length(vv) == 0) TRUE else all(map_lgl(data[vv], has_2plus))
  })]
}
build_formula <- function(lhs, rhs_terms, data = NULL) {
  rhs_terms <- unique(rhs_terms)
  if (!is.null(data)) rhs_terms <- filter_terms(rhs_terms, data)
  if (length(rhs_terms) == 0) as.formula(paste(lhs, "~ 1")) else as.formula(paste(lhs, "~", paste(rhs_terms, collapse = " + ")))
}
needed_vars_for_terms <- function(terms, data) intersect(term_vars(terms), names(data))

make_model_data <- function(data, outcome, exposure, covariates, binary = TRUE) {
  terms <- unique(c(exposure, covariates))
  needed <- unique(c("study_id", outcome, needed_vars_for_terms(terms, data)))
  d <- data %>% select(any_of(needed))
  complete_vars <- intersect(c(outcome, exposure, needed_vars_for_terms(covariates, d)), names(d))
  d <- d %>% tidyr::drop_na(any_of(complete_vars))
  if (!exposure %in% names(d) || !has_2plus(d[[exposure]])) return(tibble())
  if (binary) {
    d$outcome_numeric <- as.integer(d[[outcome]] == "Yes")
    if (!has_2plus(d$outcome_numeric)) return(tibble())
  } else {
    d$outcome_numeric <- as.numeric(d[[outcome]])
    if (all(is.na(d$outcome_numeric)) || isTRUE(sd(d$outcome_numeric, na.rm = TRUE) == 0)) return(tibble())
  }
  d
}

tidy_robust <- function(fit, vc, exponentiate, model, outcome, exposure, n_obs, n_events) {
  beta <- coef(fit); se <- sqrt(diag(vc)); z <- beta / se
  out <- tibble(term = names(beta), estimate = beta, std_error = se, statistic = z, p_value = 2 * pnorm(abs(z), lower.tail = FALSE), conf_low = beta - 1.96 * se, conf_high = beta + 1.96 * se, model = model, outcome = outcome, exposure = exposure, n_obs = n_obs, n_events = n_events)
  if (exponentiate) out <- out %>% mutate(estimate_exp = exp(estimate), conf_low_exp = exp(conf_low), conf_high_exp = exp(conf_high))
  out
}

fit_poisson_rr <- function(data, outcome, exposure, covariates = character(), label = "modified_poisson_RR") {
  d <- make_model_data(data, outcome, exposure, covariates, TRUE)
  if (nrow(d) == 0) return(tibble(model = label, outcome = outcome, exposure = exposure, error = "No valid model data"))
  rhs <- filter_terms(c(exposure, covariates), d)
  f <- build_formula("outcome_numeric", rhs, d)
  fit <- tryCatch(glm(f, data = d, family = poisson(link = "log")), error = function(e) e)
  if (inherits(fit, "error")) return(tibble(model = label, outcome = outcome, exposure = exposure, error = conditionMessage(fit)))
  tidy_robust(fit, sandwich::vcovHC(fit, type = "HC0"), TRUE, label, outcome, exposure, nrow(d), sum(d$outcome_numeric))
}
fit_poisson_rr_clustered_id <- function(data, outcome, exposure, covariates = character(), label = "clustered_id_modified_poisson_RR") {
  d <- make_model_data(data, outcome, exposure, covariates, TRUE)
  if (nrow(d) == 0) return(tibble(model = label, outcome = outcome, exposure = exposure, error = "No valid model data"))
  if (!"study_id" %in% names(d)) return(tibble(model = label, outcome = outcome, exposure = exposure, error = "study_id unavailable"))
  d$analysis_cluster_id <- ifelse(is.na(d$study_id), paste0("row_missing_id_", seq_len(nrow(d))), as.character(d$study_id))
  rhs <- filter_terms(c(exposure, covariates), d)
  f <- build_formula("outcome_numeric", rhs, d)
  fit <- tryCatch(glm(f, data = d, family = poisson(link = "log")), error = function(e) e)
  if (inherits(fit, "error")) return(tibble(model = label, outcome = outcome, exposure = exposure, error = conditionMessage(fit)))
  vc <- tryCatch(sandwich::vcovCL(fit, cluster = d$analysis_cluster_id, type = "HC0"), error = function(e) sandwich::vcovHC(fit, type = "HC0"))
  tidy_robust(fit, vc, TRUE, label, outcome, exposure, nrow(d), sum(d$outcome_numeric))
}

fit_logistic_or <- function(data, outcome, exposure, covariates = character(), label = "logistic_OR") {
  d <- make_model_data(data, outcome, exposure, covariates, TRUE)
  if (nrow(d) == 0) return(tibble(model = label, outcome = outcome, exposure = exposure, error = "No valid model data"))
  rhs <- filter_terms(c(exposure, covariates), d)
  f <- build_formula("outcome_numeric", rhs, d)
  fit <- tryCatch(glm(f, data = d, family = binomial(link = "logit")), error = function(e) e)
  if (inherits(fit, "error")) return(tibble(model = label, outcome = outcome, exposure = exposure, error = conditionMessage(fit)))
  tidy_robust(fit, sandwich::vcovHC(fit, type = "HC0"), TRUE, label, outcome, exposure, nrow(d), sum(d$outcome_numeric))
}
fit_linear_beta <- function(data, outcome, exposure, covariates = character(), label = "linear_beta") {
  d <- make_model_data(data, outcome, exposure, covariates, FALSE)
  if (nrow(d) == 0) return(tibble(model = label, outcome = outcome, exposure = exposure, error = "No valid model data"))
  rhs <- filter_terms(c(exposure, covariates), d)
  f <- build_formula("outcome_numeric", rhs, d)
  fit <- tryCatch(lm(f, data = d), error = function(e) e)
  if (inherits(fit, "error")) return(tibble(model = label, outcome = outcome, exposure = exposure, error = conditionMessage(fit)))
  tidy_robust(fit, sandwich::vcovHC(fit, type = "HC3"), FALSE, label, outcome, exposure, nrow(d), NA_integer_)
}

# -----------------------------
# 6. Descriptive tables
# -----------------------------
log_step("Creating descriptive tables")
table_vars <- c("pre_delivery_hemoglobin_g_dl", "postpartum_6h_hemoglobin_g_dl", "hemoglobin_drop_g_dl", "body_mass_index_kg_m2", "weight_kg", "height_cm", "parity", "delivery_mode", "delivery_year", "plurality_group", "gravidity_group", "grand_multiparity", "pre_delivery_anemia_hb11", "iron_use_during_pregnancy", "iv_ferric_carboxymaltose_use_during_pregnancy", "maternal_comorbidity_any", "pregnancy_complication_any", "uterotonic_agent", "postpartum_anemia_hb10", "postpartum_anemia_hb11", "hb_drop_ge_2g", "postpartum_hemorrhage", "blood_transfusion_needed")
table_vars <- table_vars[table_vars %in% names(dat) & map_lgl(dat[table_vars[table_vars %in% names(dat)]], has_2plus)]
factor_vars <- table_vars[map_lgl(dat[table_vars], ~ is.factor(.x) || is.character(.x))]
make_table1 <- function(strata, prefix) {
  if (!strata %in% names(dat) || !has_2plus(dat[[strata]])) {
    write_text(paste0("Skipped: ", strata, " is absent or has <2 levels."), file.path(OUTPUT_DIR, paste0(prefix, "_SKIPPED.txt")))
    return(invisible(NULL))
  }
  tbl <- tryCatch(tableone::CreateTableOne(vars = table_vars, strata = strata, data = dat, factorVars = factor_vars, test = TRUE, smd = TRUE), error = function(e) e)
  if (inherits(tbl, "error")) {
    write_text(conditionMessage(tbl), file.path(OUTPUT_DIR, paste0(prefix, "_ERROR.txt")))
  } else {
    write_csv(as.data.frame(print(tbl, showAllLevels = TRUE, smd = TRUE, quote = FALSE, noSpaces = TRUE)) %>% rownames_to_column("variable"), file.path(OUTPUT_DIR, paste0(prefix, ".csv")))
    write_text(capture.output(print(tbl, showAllLevels = TRUE, smd = TRUE)), file.path(OUTPUT_DIR, paste0(prefix, ".txt")))
  }
}
make_table1(PRIMARY_EXPOSURE, "01_table1_by_primary_exposure")
make_table1("cord_group_4", "01_table1_by_four_level_cord_group")
make_table1("delivery_mode", "01_table1_by_delivery_mode")

# Plots
try({
  p1 <- dat %>% filter(!is.na(cord_group_4), !is.na(hemoglobin_drop_g_dl)) %>% ggplot(aes(cord_group_4, hemoglobin_drop_g_dl)) + geom_boxplot(outlier.alpha = .3) + theme_minimal(base_size = 12) + labs(x = "Cord clamping timing", y = "Hemoglobin drop (g/dL)", title = "Hemoglobin drop by cord clamping timing") + theme(axis.text.x = element_text(angle = 30, hjust = 1))
  ggsave(file.path(OUTPUT_DIR, "01_hb_drop_by_cord_group.png"), p1, width = 8, height = 5, dpi = 300)
}, silent = TRUE)

# -----------------------------
# 7. Main regression analyses
# -----------------------------
log_step("Running conventional regression analyses")
binary_outcomes <- c("postpartum_anemia_hb10", "postpartum_anemia_hb11", "hb_drop_ge_2g", "postpartum_hemorrhage", "blood_transfusion_needed")
binary_outcomes <- binary_outcomes[binary_outcomes %in% names(dat) & map_lgl(dat[binary_outcomes[binary_outcomes %in% names(dat)]], has_2plus)]
continuous_outcomes <- c("postpartum_6h_hemoglobin_g_dl", "hemoglobin_drop_g_dl")
continuous_outcomes <- continuous_outcomes[continuous_outcomes %in% names(dat)]

reg_results <- list()
for (y in binary_outcomes) {
  reg_results[[paste(y, "unadj_rr")]] <- fit_poisson_rr(dat, y, PRIMARY_EXPOSURE, character(), "unadjusted_modified_poisson_RR")
  reg_results[[paste(y, "adj_rr")]] <- fit_poisson_rr(dat, y, PRIMARY_EXPOSURE, model_covariates, "adjusted_modified_poisson_RR")
  reg_results[[paste(y, "adj_or")]] <- fit_logistic_or(dat, y, PRIMARY_EXPOSURE, model_covariates, "adjusted_logistic_OR")
}
for (y in continuous_outcomes) {
  reg_results[[paste(y, "unadj_beta")]] <- fit_linear_beta(dat, y, PRIMARY_EXPOSURE, character(), "unadjusted_linear_beta")
  reg_results[[paste(y, "adj_beta")]] <- fit_linear_beta(dat, y, PRIMARY_EXPOSURE, model_covariates, "adjusted_linear_beta")
}
reg_all <- standardize_result_table(bind_rows(reg_results))
safe_write_csv(reg_all, file.path(OUTPUT_DIR, "02_conventional_regression_all_terms.csv"))
safe_write_csv(safe_term_filter(reg_all, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "02_conventional_regression_exposure_terms.csv"))

# Cluster-robust sensitivity for potentially repeated study IDs. This does not change
# the point estimate; it checks whether duplicate IDs materially affect inference.
cluster_results <- list()
for (y in binary_outcomes) {
  cluster_results[[y]] <- fit_poisson_rr_clustered_id(dat, y, PRIMARY_EXPOSURE, model_covariates, "clustered_id_adjusted_modified_poisson_RR")
}
cluster_all <- standardize_result_table(bind_rows(cluster_results))
safe_write_csv(cluster_all, file.path(OUTPUT_DIR, "02b_clustered_id_regression_all_terms.csv"))
safe_write_csv(safe_term_filter(cluster_all, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "02b_clustered_id_regression_exposure_terms.csv"))

# Conservative data-quality sensitivity: exclude all rows that share both study_id and
# delivery_date with another row. This avoids over-weighting potentially duplicated
# maternal deliveries or discordant same-day duplicate entries.
duplicate_exclusion_results <- tibble()
try({
  if ("duplicate_same_id_date" %in% names(dat)) {
    dd <- dat %>% filter(is.na(duplicate_same_id_date) | duplicate_same_id_date != "Yes")
    present_dup_covariates <- intersect(base_covariates, names(dd))
    dup_covariate_names <- present_dup_covariates[map_lgl(dd[present_dup_covariates], has_2plus)]
    dup_model_covariates <- c(
      setdiff(dup_covariate_names, "delivery_date_numeric"),
      if ("delivery_date_numeric" %in% dup_covariate_names) "splines::ns(delivery_date_numeric, df = 3)"
    )
    tmp <- list()
    for (y in binary_outcomes) {
      tmp[[paste0(y, "_dup_excluded")]] <- fit_poisson_rr(dd, y, PRIMARY_EXPOSURE,
                                                          dup_model_covariates,
                                                          "duplicate_same_patient_date_excluded_RR")
    }
    for (y in continuous_outcomes) {
      tmp[[paste0(y, "_dup_excluded")]] <- fit_linear_beta(dd, y, PRIMARY_EXPOSURE,
                                                           dup_model_covariates,
                                                           "duplicate_same_patient_date_excluded_beta")
    }
    duplicate_exclusion_results <- standardize_result_table(bind_rows(tmp)) %>%
      mutate(n_excluded_same_patient_date_duplicate_rows = nrow(dat) - nrow(dd))
  }
}, silent = TRUE)
safe_write_csv(duplicate_exclusion_results, file.path(OUTPUT_DIR, "02c_duplicate_same_patient_date_excluded_all_terms.csv"))
safe_write_csv(safe_term_filter(duplicate_exclusion_results, PRIMARY_EXPOSURE),
               file.path(OUTPUT_DIR, "02c_duplicate_same_patient_date_excluded_exposure_terms.csv"))

# -----------------------------
# 8. Propensity-score IPTW and overlap weighting
# -----------------------------
log_step("Running IPTW and overlap weighting")
ps_terms <- c(
  if ("pre_delivery_hemoglobin_g_dl" %in% model_covariate_names) "splines::ns(pre_delivery_hemoglobin_g_dl, df = 3)",
  if ("body_mass_index_kg_m2" %in% model_covariate_names) "splines::ns(body_mass_index_kg_m2, df = 3)",
  if ("delivery_date_numeric" %in% model_covariate_names) "splines::ns(delivery_date_numeric, df = 3)",
  setdiff(model_covariate_names, c("pre_delivery_hemoglobin_g_dl", "body_mass_index_kg_m2", "delivery_date_numeric"))
)
ps_terms <- filter_terms(ps_terms, dat)
write_csv(tibble(term = ps_terms), file.path(OUTPUT_DIR, "00_ps_formula_terms.csv"))

run_weighted <- function(estimand_type = c("ATE", "ATO")) {
  estimand_type <- match.arg(estimand_type)
  label <- ifelse(estimand_type == "ATE", "iptw", "overlap")
  needed <- unique(c(PRIMARY_EXPOSURE, needed_vars_for_terms(ps_terms, dat), binary_outcomes, continuous_outcomes, "study_id"))
  d <- dat %>% select(any_of(needed)) %>% drop_na(any_of(c(PRIMARY_EXPOSURE, needed_vars_for_terms(ps_terms, dat))))
  if (nrow(d) == 0 || !has_2plus(d[[PRIMARY_EXPOSURE]])) {
    return(list(results = standardize_result_table(tibble(error = "No valid PS data")), balance = NULL, data = d, weightit = NULL))
  }
  f_ps <- build_formula(PRIMARY_EXPOSURE, ps_terms, d)
  w <- tryCatch(
    WeightIt::weightit(f_ps, data = d, method = "glm", estimand = estimand_type, stabilize = (estimand_type == "ATE")),
    error = function(e) e
  )
  if (inherits(w, "error")) {
    return(list(results = standardize_result_table(tibble(error = conditionMessage(w))), balance = NULL, data = d, weightit = NULL))
  }
  d$.weights <- w$weights
  if (estimand_type == "ATE") {
    qs <- quantile(d$.weights, probs = TRIM_Q, na.rm = TRUE)
    d$.weights <- pmin(pmax(d$.weights, qs[1]), qs[2])
  }
  bal <- capture.output(cobalt::bal.tab(w, un = TRUE, m.threshold = .10))
  write_text(bal, file.path(OUTPUT_DIR, paste0("03_", label, "_balance.txt")))
  try({
    png(file.path(OUTPUT_DIR, paste0("03_", label, "_love_plot.png")), width = 2400, height = 1800, res = 300)
    print(cobalt::love.plot(w, threshold = .10, abs = TRUE))
    dev.off()
  }, silent = TRUE)
  res <- list()
  for (y in binary_outcomes) {
    dd <- d %>% drop_na(any_of(y)) %>% mutate(y_num = as.integer(.data[[y]] == "Yes"))
    if (nrow(dd) > 0 && has_2plus(dd$y_num) && has_2plus(dd[[PRIMARY_EXPOSURE]])) {
      des <- survey::svydesign(ids = ~1, weights = ~.weights, data = dd)
      ff <- as.formula(paste("y_num ~", PRIMARY_EXPOSURE))
      fit <- tryCatch(survey::svyglm(ff, design = des, family = quasipoisson(link = "log")), error = function(e) e)
      if (!inherits(fit, "error")) {
        tt <- broom::tidy(fit, conf.int = TRUE, exponentiate = TRUE) %>%
          mutate(model = paste0(label, "_weighted_RR"), outcome = y, exposure = PRIMARY_EXPOSURE, n_obs = nrow(dd), n_events = sum(dd$y_num))
        res[[paste(y, label)]] <- tt
      } else {
        res[[paste(y, label, "error")]] <- tibble(error = paste0("Weighted binary model failed for ", y, ": ", conditionMessage(fit)))
      }
    } else {
      res[[paste(y, label, "skipped")]] <- tibble(error = paste0("Weighted binary model skipped for ", y, ": insufficient outcome or exposure variation"))
    }
  }
  for (y in continuous_outcomes) {
    dd <- d %>% drop_na(any_of(y))
    if (nrow(dd) > 0 && has_2plus(dd[[PRIMARY_EXPOSURE]])) {
      des <- survey::svydesign(ids = ~1, weights = ~.weights, data = dd)
      ff <- as.formula(paste(y, "~", PRIMARY_EXPOSURE))
      fit <- tryCatch(survey::svyglm(ff, design = des), error = function(e) e)
      if (!inherits(fit, "error")) {
        res[[paste(y, label)]] <- broom::tidy(fit, conf.int = TRUE) %>%
          mutate(model = paste0(label, "_weighted_beta"), outcome = y, exposure = PRIMARY_EXPOSURE, n_obs = nrow(dd), n_events = NA_integer_)
      } else {
        res[[paste(y, label, "error")]] <- tibble(error = paste0("Weighted continuous model failed for ", y, ": ", conditionMessage(fit)))
      }
    } else {
      res[[paste(y, label, "skipped")]] <- tibble(error = paste0("Weighted continuous model skipped for ", y, ": insufficient data or exposure variation"))
    }
  }
  list(results = standardize_result_table(bind_rows(res)), balance = bal, data = d, weightit = w)
}
iptw <- run_weighted("ATE")
overlap <- run_weighted("ATO")
safe_write_csv(iptw$results, file.path(OUTPUT_DIR, "03_iptw_results_all_terms.csv"))
safe_write_csv(safe_term_filter(iptw$results, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "03_iptw_results_exposure_terms.csv"))
safe_write_csv(overlap$results, file.path(OUTPUT_DIR, "03_overlap_weight_results_all_terms.csv"))
safe_write_csv(safe_term_filter(overlap$results, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "03_overlap_weight_results_exposure_terms.csv"))

# -----------------------------
# 9. Matching sensitivity
# -----------------------------
log_step("Running matching sensitivity")
match_results <- tibble()
try({
  m_needed <- unique(c(PRIMARY_EXPOSURE, needed_vars_for_terms(ps_terms, dat), binary_outcomes, continuous_outcomes))
  md <- dat %>% select(any_of(m_needed)) %>% drop_na(any_of(c(PRIMARY_EXPOSURE, needed_vars_for_terms(ps_terms, dat))))
  if (nrow(md) > 0 && has_2plus(md[[PRIMARY_EXPOSURE]])) {
    mfit <- MatchIt::matchit(build_formula(PRIMARY_EXPOSURE, ps_terms, md), data = md, method = "nearest", ratio = 1, caliper = 0.2)
    mdat <- MatchIt::match.data(mfit)
    write_text(capture.output(summary(mfit)), file.path(OUTPUT_DIR, "04_matching_summary.txt"))
    tmp <- list()
    for (y in binary_outcomes) tmp[[y]] <- fit_poisson_rr(mdat, y, PRIMARY_EXPOSURE, character(), "matched_modified_poisson_RR")
    for (y in continuous_outcomes) tmp[[y]] <- fit_linear_beta(mdat, y, PRIMARY_EXPOSURE, character(), "matched_linear_beta")
    match_results <- standardize_result_table(bind_rows(tmp))
  }
}, silent = TRUE)
safe_write_csv(match_results, file.path(OUTPUT_DIR, "04_matching_results_all_terms.csv"))
safe_write_csv(safe_term_filter(match_results, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "04_matching_results_exposure_terms.csv"))

# -----------------------------
# 10. Alternative exposure definitions and dose response
# -----------------------------
log_step("Running sensitivity exposure models")
sens_results <- list()
for (expv in c("exposure_any_delay", "exposure_immediate_vs_60plus", "cord_group_4")) {
  if (expv %in% names(dat) && has_2plus(dat[[expv]])) {
    for (y in binary_outcomes) sens_results[[paste(expv, y)]] <- fit_poisson_rr(dat, y, expv, model_covariates, paste0("sensitivity_", expv, "_RR"))
    for (y in continuous_outcomes) sens_results[[paste(expv, y)]] <- fit_linear_beta(dat, y, expv, model_covariates, paste0("sensitivity_", expv, "_beta"))
  }
}
for (y in binary_outcomes) sens_results[[paste("dose", y)]] <- fit_poisson_rr(dat %>% mutate(cord_delay_min = cord_clamping_delay_seconds / 60), y, "cord_delay_min", model_covariates, "dose_per_minute_RR")
for (y in continuous_outcomes) sens_results[[paste("dose", y)]] <- fit_linear_beta(dat %>% mutate(cord_delay_min = cord_clamping_delay_seconds / 60), y, "cord_delay_min", model_covariates, "dose_per_minute_beta")
sens_all <- standardize_result_table(bind_rows(sens_results))
safe_write_csv(sens_all, file.path(OUTPUT_DIR, "05_sensitivity_and_dose_models_all_terms.csv"))
safe_write_csv(safe_term_filter(sens_all, "exposure_|cord_group_4|cord_delay_min"), file.path(OUTPUT_DIR, "05_sensitivity_and_dose_models_exposure_terms.csv"))

# -----------------------------
# 11. Subgroups, built only when column exists and is usable
# -----------------------------
log_step("Running safe subgroup analyses")
subgroups <- list()
if ("delivery_mode" %in% names(dat)) {
  subgroups$vaginal_delivery <- quo(delivery_mode == "Vaginal delivery")
  subgroups$cesarean_delivery <- quo(delivery_mode == "Cesarean delivery")
}
if ("plurality_group" %in% names(dat)) {
  subgroups$singleton_only <- quo(plurality_group == "Singleton")
  subgroups$multiple_pregnancy_only <- quo(plurality_group == "Multiple pregnancy")
}
if ("pre_delivery_anemia_hb11" %in% names(dat)) {
  subgroups$pre_delivery_anemia <- quo(pre_delivery_anemia_hb11 == "Yes")
  subgroups$no_pre_delivery_anemia <- quo(pre_delivery_anemia_hb11 == "No")
}
run_subgroup <- function(q, name) {
  d <- tryCatch(dat %>% filter(!!q), error = function(e) tibble())
  if (nrow(d) < MIN_SUBGROUP_N || !PRIMARY_EXPOSURE %in% names(d) || !has_2plus(d[[PRIMARY_EXPOSURE]])) return(tibble(subgroup = name, error = paste0("Skipped: n=", nrow(d), "; exposure levels=", ifelse(PRIMARY_EXPOSURE %in% names(d), n_distinct(d[[PRIMARY_EXPOSURE]], na.rm = TRUE), 0))))
  covs <- setdiff(model_covariates, names(select(d, where(~ !has_2plus(.x)))))
  bind_rows(
    fit_poisson_rr(d, "postpartum_anemia_hb10", PRIMARY_EXPOSURE, covs, paste0("subgroup_", name, "_RR")),
    fit_linear_beta(d, "hemoglobin_drop_g_dl", PRIMARY_EXPOSURE, covs, paste0("subgroup_", name, "_beta"))
  ) %>% mutate(subgroup = name)
}
subgroup_results <- standardize_result_table(purrr::imap_dfr(subgroups, ~ run_subgroup(.x, .y)))
safe_write_csv(subgroup_results, file.path(OUTPUT_DIR, "06_subgroup_models_all_terms.csv"))
subgroup_exposure_results <- safe_term_filter(subgroup_results, PRIMARY_EXPOSURE)
safe_write_csv(subgroup_exposure_results, file.path(OUTPUT_DIR, "06_subgroup_models_exposure_terms.csv"))

# -----------------------------
# 12. Formal interaction with delivery mode
# -----------------------------
log_step("Running formal delivery-mode interaction models")
interaction_results <- tibble()
if ("delivery_mode" %in% names(dat) && has_2plus(dat$delivery_mode)) {
  interaction_covariates <- c(
    paste0(PRIMARY_EXPOSURE, "*delivery_mode"),
    setdiff(model_covariates, "delivery_mode")
  )
  interaction_results <- bind_rows(
    fit_poisson_rr(dat, "postpartum_anemia_hb10", PRIMARY_EXPOSURE, interaction_covariates, "interaction_delivery_mode_RR"),
    fit_poisson_rr(dat, "postpartum_hemorrhage", PRIMARY_EXPOSURE, interaction_covariates, "interaction_delivery_mode_RR"),
    fit_linear_beta(dat, "hemoglobin_drop_g_dl", PRIMARY_EXPOSURE, interaction_covariates, "interaction_delivery_mode_beta")
  ) %>% standardize_result_table()
}
safe_write_csv(interaction_results, file.path(OUTPUT_DIR, "06b_delivery_mode_interaction_models_all_terms.csv"))
safe_write_csv(safe_term_filter(interaction_results, PRIMARY_EXPOSURE), file.path(OUTPUT_DIR, "06b_delivery_mode_interaction_models_exposure_terms.csv"))

# -----------------------------
# 13. Sparse outcome / Firth logistic for transfusion
# -----------------------------
log_step("Running Firth logistic for sparse transfusion outcome")
firth_out <- tibble()
try({
  y <- "blood_transfusion_needed"
  d <- make_model_data(dat, y, PRIMARY_EXPOSURE, model_covariates, TRUE)
  if (nrow(d) > 0 && sum(d$outcome_numeric) > 0 && has_2plus(d$outcome_numeric)) {
    rhs <- filter_terms(c(PRIMARY_EXPOSURE, model_covariates), d)
    ff <- build_formula("outcome_numeric", rhs, d)
    fitf <- logistf::logistf(ff, data = d)
    firth_out <- tibble(term = names(coef(fitf)), estimate = as.numeric(coef(fitf)), std_error = sqrt(diag(vcov(fitf))), p_value = as.numeric(fitf$prob), conf_low = as.numeric(fitf$ci.lower), conf_high = as.numeric(fitf$ci.upper), estimate_exp = exp(estimate), conf_low_exp = exp(conf_low), conf_high_exp = exp(conf_high), model = "firth_logistic_OR", outcome = y, exposure = PRIMARY_EXPOSURE, n_obs = nrow(d), n_events = sum(d$outcome_numeric))
  }
}, silent = TRUE)
safe_write_csv(firth_out, file.path(OUTPUT_DIR, "07_firth_sparse_transfusion.csv"))

# -----------------------------
# 14. E-values for primary IPTW RR, when available
# -----------------------------
log_step("Computing E-values where possible")
manual_evalue_rr <- function(rr) {
  rr <- as.numeric(rr)
  if (!is.finite(rr) || rr <= 0) return(NA_real_)
  rr2 <- ifelse(rr < 1, 1 / rr, rr)
  rr2 + sqrt(rr2 * (rr2 - 1))
}
manual_evalue_ci <- function(rr, lo, hi) {
  rr <- as.numeric(rr); lo <- as.numeric(lo); hi <- as.numeric(hi)
  if (!is.finite(rr) || !is.finite(lo) || !is.finite(hi) || rr <= 0 || lo <= 0 || hi <= 0) return(NA_real_)
  if (lo <= 1 && hi >= 1) return(1)
  bound <- ifelse(rr >= 1, lo, hi)
  manual_evalue_rr(bound)
}
ev <- tibble()
try({
  prim <- safe_outcome_term_filter(iptw$results, "postpartum_anemia_hb10", PRIMARY_EXPOSURE) %>% slice(1)
  if (nrow(prim) == 1) {
    rr <- suppressWarnings(as.numeric(prim$estimate_exp))[1]
    if (!is.finite(rr)) rr <- suppressWarnings(as.numeric(prim$estimate))[1]
    lo <- suppressWarnings(as.numeric(prim$conf_low_exp))[1]
    if (!is.finite(lo)) lo <- suppressWarnings(as.numeric(prim$conf_low))[1]
    hi <- suppressWarnings(as.numeric(prim$conf_high_exp))[1]
    if (!is.finite(hi)) hi <- suppressWarnings(as.numeric(prim$conf_high))[1]
    ev <- tibble(
      outcome = "postpartum_anemia_hb10",
      model = "iptw_weighted_RR",
      rr = rr,
      conf_low = lo,
      conf_high = hi,
      e_value_point = manual_evalue_rr(rr),
      e_value_ci = manual_evalue_ci(rr, lo, hi),
      interpretation_note = ifelse(lo <= 1 & hi >= 1,
                                   "Confidence interval crosses the null; CI-limit E-value is 1.",
                                   "CI-limit E-value uses the confidence-limit closest to the null.")
    )
  }
}, silent = TRUE)
safe_write_csv(ev, file.path(OUTPUT_DIR, "08_evalues_primary_iptw.csv"))

# -----------------------------
# 15. Consolidated compact outputs and plots
# -----------------------------
log_step("Writing consolidated outputs")
compact <- bind_rows(
  safe_add_source(reg_all, "conventional"),
  safe_add_source(iptw$results, "iptw"),
  safe_add_source(overlap$results, "overlap"),
  safe_add_source(match_results, "matching"),
  safe_add_source(sens_all, "sensitivity"),
  safe_add_source(cluster_all, "clustered_id"),
  safe_add_source(duplicate_exclusion_results, "duplicate_same_patient_date_excluded"),
  safe_add_source(interaction_results, "interaction"),
  safe_add_source(firth_out, "firth")
)
safe_write_csv(compact, file.path(OUTPUT_DIR, "09_all_results_all_terms.csv"))
compact_exposure <- safe_term_filter(compact, "exposure_|cord_group_4|cord_delay_min")
safe_write_csv(compact_exposure, file.path(OUTPUT_DIR, "09_all_results_exposure_terms.csv"))

# Manuscript-ready primary outcome summary across key causal/sensitivity methods
primary_summary <- compact_exposure %>%
  standardize_result_table() %>%
  dplyr::filter(outcome == "postpartum_anemia_hb10",
                stringr::str_detect(as.character(term), "Delayed_60s_or_more"),
                model %in% c("adjusted_modified_poisson_RR", "iptw_weighted_RR", "overlap_weighted_RR", "matched_modified_poisson_RR", "duplicate_same_patient_date_excluded_RR")) %>%
  dplyr::transmute(
    method = dplyr::recode(model,
                           adjusted_modified_poisson_RR = "Conventional adjusted modified Poisson",
                           iptw_weighted_RR = "Stabilized IPTW modified Poisson",
                           overlap_weighted_RR = "Overlap-weighted modified Poisson",
                           matched_modified_poisson_RR = "Propensity-score matched modified Poisson",
                           duplicate_same_patient_date_excluded_RR = "Same patient-date duplicates excluded modified Poisson",
                           .default = model),
    outcome,
    risk_ratio = dplyr::coalesce(estimate_exp, estimate),
    ci_low = dplyr::coalesce(conf_low_exp, conf_low),
    ci_high = dplyr::coalesce(conf_high_exp, conf_high),
    p_value,
    n_obs,
    n_events
  )
safe_write_csv(primary_summary, file.path(OUTPUT_DIR, "09_primary_postpartum_anemia_summary.csv"))

try({
  for (nm in c("estimate_exp", "conf_low_exp", "conf_high_exp", "estimate", "conf.low", "conf.high", "conf_low", "conf_high", "outcome", "term", "source")) { if (!nm %in% names(compact_exposure)) compact_exposure[[nm]] <- NA }
  plot_df <- compact_exposure %>% filter(outcome %in% c("postpartum_anemia_hb10", "postpartum_hemorrhage", "blood_transfusion_needed"), !is.na(estimate), !is.na(conf.low) | !is.na(conf_low_exp)) %>% mutate(est = coalesce(estimate_exp, estimate), lo = coalesce(conf_low_exp, conf.low), hi = coalesce(conf_high_exp, conf.high), label = paste(source, outcome, term, sep = " | ")) %>% filter(!is.na(est), !is.na(lo), !is.na(hi), est > 0, lo > 0, hi > 0)
  if (nrow(plot_df) > 0) {
    p <- ggplot(plot_df, aes(x = est, y = fct_reorder(label, est))) + geom_vline(xintercept = 1, linetype = 2) + geom_pointrange(aes(xmin = lo, xmax = hi)) + scale_x_log10() + theme_minimal(base_size = 10) + labs(x = "Effect estimate, log scale", y = NULL, title = "Cord-clamping effect estimates across methods")
    ggsave(file.path(OUTPUT_DIR, "09_cross_method_forest_plot.png"), p, width = 10, height = max(5, nrow(plot_df) * .25), dpi = 300)
  }
}, silent = TRUE)

notes <- c(
  "Cord clamping analysis v14 completed on the fully English translated dataset schema.",
  paste0("Input file: ", INPUT_FILE),
  paste0("Primary exposure: ", PRIMARY_EXPOSURE, " (delayed >=60 seconds vs <60 seconds)."),
  "Primary outcome: postpartum anemia at 6 hours, Hb <10 g/dL.",
  paste0("Calendar adjustment window: ", paste(EXPECTED_DATE_RANGE, collapse = " to "), "; invalid/missing dates are excluded from calendar-adjusted models."),
  paste0("Retained covariate terms: ", paste(model_covariates, collapse = ", ")), 
  "The script dynamically excludes unavailable/single-level variables and safely skips empty/error model tables.",
  "Use 03_iptw_results_exposure_terms.csv and 09_primary_postpartum_anemia_summary.csv as the primary causal tables. Calendar time is included in primary adjustment/propensity models when valid delivery dates are available. Use 02b for clustered-ID sensitivity, 02c for same patient-date duplicate-exclusion sensitivity, and 06b for formal delivery-mode interaction tests."
)
write_text(notes, file.path(OUTPUT_DIR, "10_analysis_notes_for_manuscript.txt"))
log_step(paste("Finished. Outputs written to", OUTPUT_DIR))
